---
- name: Install MySQL-python and deps
  yum: name={{ item }} state=present skip_broken=true    
  with_items:
    - MySQL-python

- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/srv/wordpress

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/wordpress/

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no
  warn: false

#- name: Create WordPress database
#  delegate_to: database
#  mysql_db: name={{ wp_db_name }} state=present
#  when: mysql_host != "localhost"

#- name: Create WordPress database (local)
#  mysql_db: name={{ wp_db_name }} state=present
#  when: mysql_host == "localhost"

#- name: Create WordPress database user
#  delegate_to: database
#  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='192.168.100.%' state=present
#  when: mysql_host != "localhost"

#- name: Create WordPress database user (local)
#  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present
#  when: mysql_host == "localhost"

- name: Copy WordPress config file
  template: src=wp-config.php dest=/srv/wordpress/

- name: Change ownership of WordPress installation
  file: path=/srv/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes

- name: install SEManage
  yum: pkg=policycoreutils-python state=present
  when: enabled_selinux

- name: set the SELinux policy for the Wordpress directory
  command: semanage fcontext -a -t httpd_sys_content_t "/srv/wordpress(/.*)?"
  when: enabled_selinux

- name: set the SELinux policy for wp-config.php
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/wp-config\.php"
  when: enabled_selinux

- name: set the SELinux policy for wp-content directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content(/.*)?"
  when: enabled_selinux

- name: set the SELinux policy for the *.php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/.*\.php"
  when: enabled_selinux

- name: set the SELinux policy for the Upgrade directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content/upgrade(/.*)?"
  when: enabled_selinux

- name: set the SELinux policy for the Uploads directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content/uploads(/.*)?"
  when: enabled_selinux

- name: set the SELinux policy for the wp-includes php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/wp-includes/.*\.php"
  when: enabled_selinux

- name: set the SELinux on all the Files
  command: restorecon -Rv /srv/wordpress
  when: enabled_selinux

- name: Start php-fpm Service
  service: name=php-fpm state=started enabled=yes
