- hosts: 127.0.0.1
  connection: local
  gather_facts: false

  vars_files:
    - ../labconfig.yml

  tasks:
    - name: Setup network
      include: setup-network.yml

    - name: Setup LXD
      include: setup-lxd.yml    

    - name: Setup SSH
      include: setup-ssh.yml    

    - name: Make systemd mount point script (Alpine workaround)
      copy:
        dest: /etc/motd
        content: |
          Wellcome to Lab VM

          TODO Need to put something smart here

  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted