---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: enabled_selinux

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mariadb

- name: Configure telegraf pluding for MySQL
  copy:
    src: telegraf.d
    dest: /etc/telegraf/
  notify: restart telegraf

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: Create DB super user
  mysql_user: name=root password=root priv=*.*:ALL host='192.168.100.%' state=present

- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
  when: enabled_firewalld